# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: janicejl.com
description: >-
  Hi -- Thanks for dropping by this website! My name is Janice, and I'm a 
  Software Engineer at X - The Moonshot Factory. My goal is to contribute my
  skills to climate action. Working with and leading teams to collectively 10x
  our impact on the planet. When not working, I enjoy CrossFit, drums and 
  cooperative board games.
github_username: janicejl
minimal_mistakes_skin: default # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: false

logo: "/assets/favicon/favicon-transparent-32x32.png"
masthead_title: " "

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: PST

include:
  - _pages
  - _drums

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata

author:
  name   : "Janice"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software Engineer for Good"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://janicejl.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/janicejl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/janicejl"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@jrumtime5515"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://janicejl.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/janicejl"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/janicejl"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@jrumtime5515"

collections:
  drums:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: about
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _drums
  - scope:
      path: ""
      type: drums
    values:
      layout: single
      author_profile: true
      sitemap: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-0T0C3W77FQ"
    anonymize_ip: true