# Site settings
title: Janice Leung
email: jjw1707@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Janice Leung. I am a computer science student at the University of Southern California.
  Please take a look at my site. Thanks!
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://www.janicejl.com"
url: "http://jjw1707.github.io"
#url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: j0krester
github_username: jjw1707
paginate: 5
paginate_path: "/projects/page:num"

# Build settings
markdown: kramdown
